# Generated by Django 4.2.2 on 2023-06-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_one",
            field=models.ImageField(upload_to="media/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_two",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
